AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 deployment

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f58b397bc5c1f2e8  # change based on region
      SecurityGroupIds:
        - !Ref InstanceSG

  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
